[package]
name = "tsctl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["env"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
